services:
  bot:
    build:
      context: .
    container_name: support-bot
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - support-bot
    tty: true
    privileged: true
    

  redis:
    image: redis:alpine
    container_name: support-redis
    restart: always
    volumes:
      - ./redis/data/:/data
    networks:
      - support-bot
    tty: true

networks:
  support-bot:
