services:
  bot:
    build:
      context: .
    container_name: app
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - interconnect
    tty: true
    

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./redis/data/:/data
    networks:
      - interconnect
    tty: true

networks:
  interconnect:
