services:
  bot:
    build:
      context: .
    container_name: supportbot-app
    env_file: "stack.env"
    restart: always
    depends_on:
      - redis
    networks:
      - interconnect
    tty: true
    

  redis:
    image: redis:alpine
    container_name: supportbot-db
    hostname: redis
    restart: always
    volumes:
      - ./redis/data/:/data
    networks:
      - interconnect
    tty: true

networks:
  interconnect:
